### ISSUE TITLE
Error generating

### ISSUE THREAD

**Issue by Heesel** [alpertunga-bile/prompt-markdown-parser#1]
**Describe the bug**
when I am trying to generate a prompt, I get this error:
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used. 

Error loading "D:\stable-diffusion\prompt-markdown-parser\venv\Lib\site-packages\torch\lib\caffe2_nvrtc.dll" or one of its dependencies.
Finished successfully

**Expected behavior**
To generate a prompt

**Screenshots**
![image](https://github.com/alpertunga-bile/prompt-markdown-parser/assets/49622357/18d143c0-f5b9-49c5-9d65-9aba6a5ab7a9)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
No additional content

**Comment by alpertunga-bile** [comment]
Hello! There seems to be a misunderstanding regarding which AI model to use. In this menu, text generator models should be used instead of stable diffusion models to generate prompts. I have provided tutorials for each menu in the readme file. You can see how to create your own text generator model and use it.
